"""Backend-neutral graph repository protocol."""

from __future__ import annotations

from typing import Any, Protocol

from ..schemas import (
    BaselineMatrixEntry,
    BenchmarkMatrixEntry,
    CandidateEdge,
    DatasetMatrixEntry,
    MethodFamily,
    PaperProfile,
    SurveyTaxonomy,
    Theme,
    VerifiedEdge,
)


class GraphRepositoryProtocol(Protocol):
    """Minimal routing-graph API used by LOGOS workflow and QA."""

    def connect(self) -> "GraphRepositoryProtocol": ...
    def close(self) -> None: ...
    def setup_schema(self) -> None: ...
    def create_paper_node(self, profile: PaperProfile) -> None: ...
    def create_theme_nodes(self, themes: list[Theme]) -> None: ...
    def create_method_family_nodes(self, families: list[MethodFamily]) -> None: ...
    def create_benchmark_nodes(self, benchmarks: list[BenchmarkMatrixEntry]) -> None: ...
    def create_dataset_nodes(self, datasets: list[DatasetMatrixEntry]) -> None: ...
    def create_baseline_nodes(self, baselines: list[BaselineMatrixEntry]) -> None: ...
    def create_paper_relationships(
        self,
        profile: PaperProfile,
        taxonomy: SurveyTaxonomy,
    ) -> None: ...
    def create_candidate_relation(self, edge: CandidateEdge) -> None: ...
    def update_relation_status(self, edge: VerifiedEdge) -> None: ...
    def search_papers_by_theme(self, theme_name: str) -> list[dict[str, Any]]: ...
    def search_papers_by_benchmark(self, benchmark_name: str) -> list[dict[str, Any]]: ...
    def get_paper_neighbors(
        self,
        paper_id: str,
        min_confidence: float = 0.5,
    ) -> list[dict[str, Any]]: ...
    def fulltext_search_papers(
        self,
        query_text: str,
        limit: int = 10,
    ) -> list[dict[str, Any]]: ...
